apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: website-db-vault-kaf-redis-arg-kust-kyv-gra-loki-temp-pgadm-chat-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/exea-centrum/website-db-vault-kaf-redis-arg-kust-kyv-gra-loki-temp-pgadm-chat.git'
    targetRevision: main
    path: manifests/base
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: davtroallinone
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
