apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: website-db-vault-kaf-redis-arg-kust-kyv-gra-loki-temp-pgadm-chat
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/exea-centrum/website-db-vault-kaf-redis-arg-kust-kyv-gra-loki-temp-pgadm-chat.git
    targetRevision: main
    path: manifests/base
    kustomize:
      buildOptions: --load-restrictor=LoadRestrictionsNone
  destination:
    server: https://kubernetes.default.svc
    namespace: davtrowebdbvault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - ApplyOutOfSyncOnly=true
      - Validate=false
  retry:
    limit: 5
    backoff:
      duration: 10s
      factor: 2
      maxDuration: 2m
