apiVersion: v1
kind: ConfigMap
metadata:
  name: website-db-vault-kaf-redis-arg-kust-kyv-gra-loki-temp-pgui-config
  namespace: davtrowebdbvault
data:
  DATABASE_URL: "dbname=appdb user=appuser password=apppass host=postgres"
