apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config-kraft
  namespace: davtrowebdbvault
data:
  KAFKA_CLUSTER_ID: "4mUj5vFk3tW7pY0iH2gR8qL6eD9oB1cZ"
  KAFKA_NODE_ID: "0"
  KAFKA_PROCESS_ROLES: "broker,controller"
  # Wymaga FQDN: kafka-0.kafka
  KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
  KAFKA_CONTROLLER_QUORUM_VOTERS: "0@kafka-0.kafka:9093"
  ALLOW_PLAINTEXT_LISTENER: "yes"
  KAFKA_CFG_LOG_DIRS: "/bitnami/kafka/data/kraft-combined-logs"
  # Dodatkowe: nowszy image i tag
  KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"
