apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: davtrowebdbvault
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'fastapi'
        metrics_path: /metrics
        # Używamy nowej, krótszej nazwy PROJECT
        static_configs:
          - targets: ['webstack-gitops:8000'] 
