apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: davtroallinone
type: Opaque
stringData:
  username: postgres
  password: postgres123
---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: davtroallinone
type: Opaque
stringData:
  password: pgadmin123
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: davtroallinone
type: Opaque
stringData:
  password: grafana123
