apiVersion: v1
kind: Service
metadata:
  name: website-db-vault-kaf-redis-arg-kust-kyv-gra-loki-temp-pgadm-chat-svc
  namespace: davtroallinone
spec:
  selector:
    app: website-db-vault-kaf-redis-arg-kust-kyv-gra-loki-temp-pgadm-chat-app
  ports:
    - port: 80
      targetPort: 8080
