apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
  namespace: davtroallinone
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: website-db-vault-kaf-redis-arg-kust-kyv-gra-loki-temp-pgadm-chat
  namespace: davtroallinone
