apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-agent-injector
  namespace: davtrowebdbvault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-agent-injector
  template:
    metadata:
      labels:
        app: vault-agent-injector
    spec:
      containers:
        - name: vault-k8s
          image: hashicorp/vault-k8s:1.9.0
          args: ["controller"]
